# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0002_nonseamlesstransaction_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='address1',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='address2',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='basket',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='custom_note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Custom Note'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='drop_category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Drop Category'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='error_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Error Code'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='error_message',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='firstname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='lastname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='note_category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Note Category'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='offer_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Offer Key'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='orderid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='productinfo',
            field=models.CharField(max_length=100, verbose_name='Product info'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='raw_request',
            field=models.TextField(max_length=1024, verbose_name='Raw Request'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='raw_response',
            field=models.TextField(max_length=1024, verbose_name='Raw Response'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='response',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('W', 'Awaiting Confirmation'), ('S', 'Success'), ('F', 'Failure'), ('C', 'Cancelled')], max_length=2, null=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='nonseamlesstransaction',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code'),
        ),
    ]
